AssestOrderingApplication/Controllers/AdminController.cs
using AssestOrderingApplication.Services;
using Microsoft.AspNetCore.Mvc;

namespace AssestOrderingApplication.Controllers
{
    public class AdminController : Controller
    {
        private readonly AdminService _adminService;
        public OrderService OrderService;

        public AdminController(AdminService adminService, OrderService orderService)
        {
            OrderService = orderService;
            _adminService = adminService;
        }


        public IActionResult Index()
        {
            ViewData["IsAdmin"] = IsAdmin();
            return View();
        }
        public bool IsAdmin()
        {
            return _adminService.IsAdmin(User.Identity.Name);
        }
        
    }
}

AssestOrderingApplication/Controllers/OrderController.cs
using AssestOrderingApplication.Services;
using Microsoft.AspNetCore.Mvc;

namespace AssestOrderingApplication.Controllers
{
    public class OrderController : Controller
    {
        public OrderService OrderService;
        public OrderController(OrderService orderService)
        {
            OrderService = orderService;
        }
        public IActionResult Index()
        {
            var orders = OrderService.GetOrderById(User.Identity.Name.Split('\\').Last());
            return View(orders);
        }
    }
}

AssestOrderingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssestOrderingApplication</title>

    <!--
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/AssestOrderingApplication.styles.css" asp-append-version="true" />
    -->

    <link rel="stylesheet" href="~/css/site.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            font-family: 'Poppins', sans-serif;
        }

        .footer {
            margin-top: auto;
            background-color: #1E2556;
            color: white;
            padding: 20px 0;
            height: auto;
            align-items: center;
            justify-content: center;
        }

            .footer p {
                margin: 0;
                padding: 0;
            }

        .btn-custom {
            background-color: #1E2556;
            color: white;
            margin: 2px;
        }

            .btn-custom:hover {
                background-color: white;
                color: #1E2556;
                border: 2px solid #1E2556;
            }

        .navbar-custom {
            background-color: white;
        }

        .hidden {
            display: none;
        }

        .poppins-regular {
            font-family: "Poppins", sans-serif;
            font-weight: 400;
            font-style: normal;
        }

        .poppins-medium {
            font-family: "Poppins", sans-serif;
            font-weight: 500;
            font-style: normal;
        }

        .poppins-bold {
            font-family: "Poppins", sans-serif;
            font-weight: 700;
            font-style: normal;
        }

        .poppins-semibold {
            font-family: "Poppins", sans-serif;
            font-weight: 600;
            font-style: normal;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-custom navbar-expand-lg justify-content-between align-content-lg-center">
        <div class="navbar-brand d-flex align-items-center">
            <img src="~/images/comp-logo.png" alt="Logo" height="20">
            <button class="btn ml-2" onclick="location.href='@Url.Action("Index", "Home")'">Home</button>
            <button class="btn ml-2" onclick="location.href='@Url.Action("Index", "Asset")'">Assets</button>
            <button class="btn ml-2" onclick="location.href='@Url.Action("Approval", "Asset")'">Approvals</button>
            <a href="@Url.Action("Index","Order")"><button class="btn ml-2">Orders</button></a>
        </div>
        <div class="ml-auto d-flex align-items-center">
            <button class="btn ml-2" onclick="location.href='@Url.Action("Request", "Asset")'">Cart</button>

            <a href="@Url.Action("Index","Admin")"><button class="btn ml-2">Admin</button></a>
                <span class="ml-4">@User.Identity.Name.Split('\\').Last()</span>
        </div>
    </nav>


    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer footer-bottom text-center">
        <p>For any queries contact: support-it@insightsoftware.com</p>
        <p>© . All Rights Reserved.</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>